Repository ORGO-Official/orgo-backend, pull requests merged in 2023-09, with the labels that each got.

#46 [Refactor] 완등 기록 조회 API 수정 및 코드 리팩토링
  .gitignore
  build.gradle
  src/main/generated/orgo/backend/domain/_4climbingRecord/mapper/ClimbingRecordMapperImpl.java
  src/main/java/orgo/backend/domain/_4climbingRecord/api/ClimbingRecordController.java
  src/main/java/orgo/backend/domain/_4climbingRecord/application/ClimbingRecordService.java
  src/main/java/orgo/backend/domain/_4climbingRecord/mapper/ClimbingRecordMapper.java
  src/test/resources/application-inttest.yml
  src/test/resources/application-test.yml
Labels: 1️⃣ Ver 1.0, ♻️ Refactor

#47 [Refactor] 완등 기록 조회 API 반환형 수정
  .gitignore
  src/main/generated/orgo/backend/domain/_4climbingRecord/mapper/ClimbingRecordMapperImpl.java
  src/main/java/orgo/backend/domain/_4climbingRecord/controller/ClimbingRecordController.java
  src/main/java/orgo/backend/domain/_4climbingRecord/dto/ClimbingRecordDto.java
  src/main/java/orgo/backend/domain/_4climbingRecord/dto/MyClimbingRecordDto.java
  src/main/java/orgo/backend/domain/_4climbingRecord/mapper/ClimbingRecordMapper.java
  src/main/java/orgo/backend/domain/_4climbingRecord/service/ClimbingRecordService.java
  src/test/java/orgo/backend/domain/_4climbingRecord/ClimbingRecordTest.java
  src/test/java/orgo/backend/domain/_4climbingRecord/controller/ClimbingRecordControllerTest.java
Labels: 1️⃣ Ver 1.0, ♻️ Refactor

#52 [fix] 카카오맵 링크 없는 장소가 반환값에 포함되는 문제 해결
  src/docs/asciidoc/index.adoc
  src/main/java/orgo/backend/domain/_3mountain/service/placelinkfinder/KakaoMapPlaceLinkFinder.java
  src/test/java/orgo/backend/integrationtest/MountainApiTest.java
Labels: 🪲 Bug, 2️⃣ Ver 2.0

#53 [Refactor] 데이터 추가
  src/main/resources/data.sql
Labels: 🔨 Chore, 2️⃣ Ver 2.0

#55 [Feature] 뱃지 엔티티 추가
  src/main/java/orgo/backend/domain/_5badge/entity/Badge.java
  src/main/java/orgo/backend/domain/_5badge/entity/BadgeGroup.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordCountBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordHeightBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordMonthBadge.java
  src/main/java/orgo/backend/domain/_5badge/repository/BadgeRepository.java
  src/main/java/orgo/backend/global/config/jpa/BaseTimeEntity.java
  src/main/resources/data.sql
  src/test/java/orgo/backend/domain/_5badge/entity/BadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/entity/RecordCountBadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/entity/RecordHeightBadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/entity/RecordMonthBadgeRepositoryTest.java
Labels: 🌟 Feature, ♻️ Refactor, 2️⃣ Ver 2.0

#57 [Feature] 획득/미획득 뱃지 조회 구현
  src/docs/asciidoc/index.adoc
  src/main/java/orgo/backend/domain/_2user/entity/User.java
  src/main/java/orgo/backend/domain/_3mountain/entity/Mountain.java
  src/main/java/orgo/backend/domain/_5badge/controller/BadgeController.java
  src/main/java/orgo/backend/domain/_5badge/dto/BadgeDto.java
  src/main/java/orgo/backend/domain/_5badge/entity/Badge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordCountBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordHeightBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordMonthBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/acquisition/Acquisition.java
  src/main/java/orgo/backend/domain/_5badge/repository/AcquisitionRepository.java
  src/main/java/orgo/backend/domain/_5badge/repository/BadgeRepository.java
  src/main/java/orgo/backend/domain/_5badge/service/BadgeService.java
  src/main/resources/data.sql
  src/test/java/orgo/backend/domain/_2user/controller/UserControllerTest.java
  src/test/java/orgo/backend/domain/_5badge/controller/BadgeControllerTest.java
  src/test/java/orgo/backend/domain/_5badge/repository/AcquisitionRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/repository/BadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/repository/RecordCountBadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/repository/RecordHeightBadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/repository/RecordMonthBadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/service/BadgeServiceTest.java
  src/test/java/orgo/backend/integrationtest/BadgeApiTest.java
  src/test/java/orgo/backend/setting/MockEntityFactory.java
  src/test/resources/data.sql
Labels: 🌟 Feature, 2️⃣ Ver 2.0

#59 [Feature] RecordCountBadge - Mountain 연관관계 제거
  src/main/java/orgo/backend/domain/_5badge/entity/RecordCountBadge.java
  src/main/resources/data.sql
  src/test/java/orgo/backend/domain/_5badge/repository/BadgeRepositoryTest.java
  src/test/java/orgo/backend/domain/_5badge/repository/RecordCountBadgeRepositoryTest.java
  src/test/java/orgo/backend/integrationtest/BadgeApiTest.java
Labels: ♻️ Refactor, 2️⃣ Ver 2.0

#63 [Feature] 완등 인증 후 발급 가능한 뱃지 발급 기능 구현
  src/main/java/orgo/backend/domain/_2user/entity/User.java
  src/main/java/orgo/backend/domain/_4climbingRecord/repository/ClimbingRecordRepository.java
  src/main/java/orgo/backend/domain/_4climbingRecord/service/ClimbingRecordService.java
  src/main/java/orgo/backend/domain/_5badge/entity/Badge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordCountBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordHeightBadge.java
  src/main/java/orgo/backend/domain/_5badge/entity/RecordMonthBadge.java
  src/main/java/orgo/backend/domain/_5badge/service/BadgeFactory.java
  src/main/java/orgo/backend/domain/_5badge/service/RecordBadgeFactory.java
  src/test/java/orgo/backend/domain/_2user/entity/UserTest.java
  src/test/java/orgo/backend/domain/_5badge/service/RecordBadgeFactoryTest.java
  src/test/java/orgo/backend/setting/MockEntityFactory.java
Labels: 🌟 Feature, 2️⃣ Ver 2.0
